apiVersion: v1
kind: Service
metadata:
  name: results-svc
  labels:
     app: results-app
spec:
  type: LoadBalancer
  ports: 
   - targetPort: 80
     port: 80
     nodePort: 32555
  selector:
    app: results-app
