apiVersion: v1 
kind: Pod
metadata:
 name: vote-app-pod
 labels:
   app: vote-app 
spec:
 containers:
  - name: vote-app-con
    image: dockersamples/examplevotingapp_vote:dotnet-alpine
    ports:
      - containerPort: 80
