apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    app: worker-app
spec:
  containers:
    - name: worker-con
      image: dockersamples/examplevotingapp_worker:latest
      ports:
        - containerPort: 80
